### NumPy - Numerical Python
- It is the foundation of data science. it allows for efficient operations on the data structure often used in machine learning. The reason it is important for data science with python is that almost all of the libraries in the PyData Ecosystem rely on NumPY as one of the building blocks

##### NumPy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. NumPy arrays essentially come in vectors and matrices.
- Vectors = 1-Dimensional
- Matrix = 2-Demensional


In [1]:
import numpy as np

In [2]:
# How to create numpy array from a list

num = list(range(10))
num

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
num_array = np.array(num)
num_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
num_array.shape

(10,)

In [4]:
type(num_array)

numpy.ndarray

In [5]:
# how to create a matric using a list

num1 = list(range(1,4))
num2 = list(range(4,7))
num3 = list(range(7,10))

print(num1,num2,num3)

[1, 2, 3] [4, 5, 6] [7, 8, 9]


In [6]:
matrix = np.array([num1, num2, num3])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
matrix.shape

(3, 3)

Built in methods in NumPy-arange, Reshape,zeros,ones,linspace, eyes

In [12]:
test = np.arange(10)
test

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
test = np.arange(1,11)
test

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [15]:
test_new = test.reshape(5,2)
test_new

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [22]:
test2 = np.arange(1,26)
test2.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [24]:
#Zeros
# 1D
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [26]:
# 2D
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [27]:
#ones
# 1D
np.ones(5)

array([1., 1., 1., 1., 1.])

In [29]:
# 2D
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
# Linspace --- gives evenly space numbers
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [32]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [35]:
#eye --- identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### Indexing and Slicing

In [38]:
test = np.arange(1,37)
test

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36])

In [39]:
test[-1]

36

In [40]:
test[35]

36

In [41]:
test[0:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
test[1: :2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36])

In [48]:
test[0: :2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35])

In [51]:
test[4::5]

array([ 5, 10, 15, 20, 25, 30, 35])

In [54]:
test2 = test.reshape(6,6)
test2

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [56]:
test2.shape

(6, 6)

In [58]:
# indexing
test2[0]

array([1, 2, 3, 4, 5, 6])

In [61]:
test2[4][3]

28

In [62]:
test2[5][3:]

array([34, 35, 36])

In [64]:
test2[3][1:4]

array([20, 21, 22])

In [67]:
#[row, column]
test2


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [66]:
test2[1:4]

array([[ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [70]:
test2[1:4, 3:6]

array([[10, 11, 12],
       [16, 17, 18],
       [22, 23, 24]])

In [71]:
test2[2:5, 1:4]

array([[14, 15, 16],
       [20, 21, 22],
       [26, 27, 28]])

#### Random - Rand, Randn and Randint

In [73]:
# rand -- Random numbers (0 and 1)
test = np.random.rand(5)
test

array([0.37479162, 0.92505221, 0.52034055, 0.24613268, 0.17187633])

In [77]:
test = np.random.rand(2,2)
test

array([[0.58790225, 0.03999974],
       [0.18762813, 0.65557237]])

In [79]:
# randn -- Random numbers from a normal distribution(mean=0 variance=1)

num = np.random.randn(5)
num

array([-0.28469894, -2.12892636, -0.23628513, -0.919099  , -1.51296475])

In [80]:
num = np.random.randn(5,4)
num

array([[-0.45938287, -0.67646578,  0.68682354, -1.34595656],
       [ 1.80842128, -0.28720198, -1.83769842, -1.74248322],
       [-0.62280628, -1.42234229, -0.4561009 ,  1.1925465 ],
       [ 0.48850321, -0.5118537 ,  2.47170334, -1.15738899],
       [ 0.44153208, -0.20137051,  1.02929805,  0.30047086]])

In [83]:
# Randint = randon integars(low value--> high value)
test = np.random.randint(10,50)
test

30

In [85]:
test2 = np.random.randint(10,50,4)
test2

array([48, 38, 36, 37])

In [87]:
# MIN, MIN, ARGMAX, ARGMIN

test2.max()

48

In [88]:
test2.min()

36

In [89]:
#index of the min value
test2.argmin()

2

In [91]:
#index of the max value
test2.argmax()

0